PUZZLE_WIDTH_STR =          8
PUZZLE_HEIGHT_STR =         8
WORD_BANK_WORD_ENTRY_STR =  ("{}. ")
PRINTING_PUZZLE_STR =       ("This is what the puzzle looks like: ")
SOLVE_TIME_STR =            ("Solved in {} second{} and {} millisecond{}")
DISPLAYING_SOLUTIONS_STR =  ("Displaying solutions...")
NO_SOLUTIONS_STR =          ("No solutions found. Start next puzzle?(y/n): ")
SOLVING_STR =               ("Solving...")
LEFT_BTN_TEXT =             ("<")
RIGHT_BTN_TEXT =            (">")
ENTER_BTN_TEXT =            ("Enter")
NEW_PUZZLE_BTN_TEXT =       ("Next puzzle")
GUI_SELECTED_TILE_COLOR =   ("floral white")
GUI_DESELECTED_TILE_COLOR = ("rosy brown")